# Generated by Django 5.1.1 on 2024-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_signup_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='signup_location',
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
